- name: Prepare backend server for Expens eproject
  hosts: backend.kotte.site
  become: true
  vars:
    packages:
    - nodejs
    - mysql
    mysql_password: ExpenseApp@1
    db_host: mysql.kotte.site
  tasks:
  - name: Disable default nodeJS
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable nodeJS 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Enable nodejs service
    ansible.builtin.service"
      name: nodejs
      state: started
      enabled: yes

  - name: Install nodeJS 
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop: "{{packages}}"
    
  - name: create expense user
    ansible.builtin.user:
      name: expense
  

  
