- name: Prepare frontend server for expense project
  become: true
  hosts: frontend.kotte.site
  tasks:
  - name: Install nginx service
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: Start the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: remove the content of html directory if already exists
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent
    
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the frontend code from internet
    ansible.builtin.get_url:
      url: curl -o /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: unarchive the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
