- name: Create mysql server for expense project
  hosts: mysql
  become:  true
  vars:
    mysql_password: ExpenseApp@1
    db_host: mysql.kotte.site
  tasks:
  - name: Install mysql service
    ansible.builtin.package:
      name: mysql-server
      state: presnt
  
  - name:  Start and enable the mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: chack if the toot password is alrady set
    ansible.builtin.command: "mysql -h {{db_host}} -u root -p{{mysql_password}}"
    register: mysql_info

  - name: print the mysql-info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"


  # - name: Setting up root password
  #   ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql-password}}"

  